### ISSUE TITLE
Joining forces 

### ISSUE THREAD

**Issue by bySabi** [jtlapp/subtap#1]
Hi @jtlapp maybe we can work together. I interested too on improve current TAP tools.
See my TAP related projects:
https://github.com/bySabi/tapa
https://github.com/bySabi/tap-lochnest
https://github.com/bySabi/karma-tap-pretty-reporter

I'm too current mantainer of:
https://github.com/bySabi/karma-tap

Don´t hesitate on contact me anytime

**Comment by jtlapp** [comment]
That's interesting work you're doing! I hope to be posting my final round of enhancements this evening, which should make the character of this particular runner apparent. After that I need to make test suites for it and document it. I haven't been making unit tests as I go because the thing keeps evolving, and I'm only just coming to understand what it needs to be. It's also giving me quite an education in node and npm.

This particular runner is one people would use for working bugs out, not necessarily for ensuring backward compliance over time.

I'll be looking forward to your feedback, once I make the nature of this thing clear.  Thanks for contacting me!

**Comment by jtlapp** [comment]
Hey @bySabi, I'm moving test execution to a child process so that my parent process can properly handle a crashing test file. The standard way to do this is to run each test file in a new child process. That way, if any child process crashes, the runner can continue with subsequent test files.

The point of subtap is to give each root-level test a number so that the programmer can choose to debug one test at a time by number. (The numbers will change over time, but should be static for the duration of a debugging session.) So if a test file crashes, that would mess up the numbering, so subtap has to bomb out of testing.

Is there any other reason to run each test file in its own process? Starting a new process for each test guarantees the initial state, making it the better choice. But if I were to have a single child process run all test files until either the first crash or completion, I could spare the OS a ton of spawning, taxing the computer less and potentially doing the whole run faster.

Is that tradeoff worth it? Do you know of any clear examples where resetting the environment by starting a new child for each test file seems necessary? Node seems really good at isolating modules, assuming that they don't use globals (`global.*`). The only situation I can think of is if two test files differently configure the singleton state of some poorly-designed node module.

**Comment by jtlapp** [comment]
I think I've got my answer. It seems reasonable for a module to implement a stateful singleton class within a particular application. If I don't run each test file in its own process, the tests would have to reliably reset the state of this singleton class. It may also not make sense to build a state reset into such classes except for purposes of supporting testing. If I isolate each test file in its own child process, I eliminate the need for developers to implement state resets.

So I'll go ahead and run each test file in its own child process like everyone else does.

**Comment by bySabi** [comment]
He @jtlapp, I don´t have too much knowledge in order to answer your questions but I wondering what you wanna do with `subtap`? .. What is that bad with `tap` or `tape`?

Follow the "one process per test" approach  is more simple to develop and fit well with UNIX tools philosophy

**Comment by jtlapp** [comment]
`subtap` lets you easily run a selected subset of an entire test suite -- just the particular test that failed, for example. You won't have to work to isolate the test for debugging; subtap will do it for you. I'll explain more in the readme. Plus, it can optionally be used as a pretty-printer.

**Comment by bySabi** [comment]
I will wait doc´s then :+1: 

Maybe I can do a similar test fail isolator with  https://github.com/bySabi/tapa
Is in the roadmap add "tap tools" API decorators to `tapa` and this will be the starting point for build many tools on top of it, including   https://github.com/bySabi/tap-lochnest and "fail test isolator"

**Comment by jtlapp** [comment]
Hello @bySabi. I just posted a full description of this tool. I'd love to know what you think of it. I keep mucking with the output format and want to wait until it's settled before writing tests. Unfortunately, it doesn't work with the version of `tap` that @isaacs posted this weekend, so you'll need to use a version prior to 7.0.0. I'll be looking into the problem. Thanks for your help!

**Comment by jtlapp** [comment]
I have resolved the incompatibility with tap 7.0.0 by mapping the TAP output of 7.0.0 to the expectations of tap-parser 1.2.2. That way subtap works no matter what version of tap the test suite uses.

**Comment by bySabi** [comment]
I can`t review this project well cause time contrains but I will do soon.

I just scratch the surface but it´s look good, good work !!

One things, it´s  `tape` compatible or only `node-tap`?

I don´t like integration of pretty output code with test runner cause it break UNIX tools philosophy but I undestand that recreate a tap parser only for make prettifiers tools really don´t make same.
Maybe you can add one API for 3rd party prettifiers on top of  `subtap`

**Comment by jtlapp** [comment]
Hi @bySabi. It only works with `node-tap` because it does some monkey-patching.

It's primary purpose is to extend the functionality of `tap`, not to prettify. Prettifying was only an incidental need. You can run my tool with the `--tap` option to skip my prettifying and output the results of the extended `tap` to any tool you want. Maybe I should have made that clear.

I designed it to be extensible in an OO way. People can subclass my TapReceiver and BaseReport classes to create new kinds of output. The docs don't mention that.

**Comment by jtlapp** [comment]
Closing this to keep things tidy, but we can keep the conversation going.
